##===- projects/sample/tools/sample/Makefile ---------------*- Makefile -*-===##

#
# Indicate where we are relative to the top of the source tree.
#
LEVEL=../..

SC_FLAGS = -I/usr/include/i386-linux-gnu/c++/4.7
CFLAGS += $(SC_FLAGS)
CXXFLAGS += $(SC_FLAGS)

#
# Give the name of a library.  This will build a dynamic version.
#
LIBRARYNAME=sample

#
# Include Makefile.common so we know what to do.
#
include $(LEVEL)/Makefile.common

