##===- projects/sample/tools/sample/Makefile ---------------*- Makefile -*-===##

#
# Indicate where we are relative to the top of the source tree.
#

LIBRARYNAME = LLVMcfi_pass
LOADABLE_MODULE = 1
USEDLIBS =

SC_FLAGS = -I/usr/include/i386-linux-gnu/c++/4.7
CFLAGS += $(SC_FLAGS)
CXXFLAGS += $(SC_FLAGS)

#
# Include Makefile.common so we know what to do.
#
include $(LEVEL)/Makefile.common

