#!/usr/bin/env python

import os
import sys
import subprocess
import fileinput

def usage():
    use = "\n\tUsage: get_stats <dir> <outfile>\n\
\tdir - directory containing llvm bitcode files to harden\n"
    print(use)

def main():
    if len(sys.argv) < 3:
        usage()
        sys.exit(1)

    dir = sys.argv[1]
    outfile = sys.argv[2]

    os.chdir(dir)
    binfiles = []
    for file in os.listdir("./"):
        if len(file.split(".")) == 1 and "Make" not in file:
            binfiles.append(os.path.abspath(file))

    for file in binfiles:
        print("getting size from " + file)

	subprocess.check_call(["arm-linux-gnueabi-size", file])

if __name__ == "__main__":
    main()
