#!/usr/bin/env python

#prints sizes of all binary files in a folder

import os
import sys
import subprocess
import fileinput

def usage():
    use = "\n\tUsage: get_sizes <dir>\n\
\tdir - directory containing binary files\n"
    print(use)

def main():
    if len(sys.argv) < 2:
        usage()
        sys.exit(1)

    dir = sys.argv[1]

    os.chdir(dir)
    binfiles = []
    for file in os.listdir("./"):
        if len(file.split(".")) == 1 and "Make" not in file:
            binfiles.append(os.path.abspath(file))

    for file in binfiles:
        print("getting size from " + file)

	subprocess.check_call(["arm-linux-gnueabi-size", file])

if __name__ == "__main__":
    main()
