#!/usr/bin/env python

#Used for compiling Coreutils

import os, sys

def main():
    #remove -Wint-to-pointer-cast and -Werror for chroot
    #clang will error out when gcc doesn't
    str = ' '.join(sys.argv)
    if "-Werror" in str:
	sys.argv.remove("-Werror")
	
    os.execvp("clang", ["clang", "-emit-llvm", "-static",
        "-usr-gold-plugin", "-Wl,-plugin-opt=also-emit-llvm",
        "-target", "armv7a-linux-gnueabi",
        ] + sys.argv[1:])
   
    return 1

if __name__ == '__main__':
    main()
